x-assets: &default-assets
  build:
    context: "."
    target: "ruby"
    args: 
      - "RAILS_ENV=${RAILS_ENV:-production}"
      - "NODE_ENV=${NODE_ENV:-production}"
  env_file:
    - ".env"
  tty: true
  volumes:
    - ".:/app"

services:
  js:
    <<: *default-assets
    command: "yarn build --watch"
  css:
    <<: *default-assets
    command: "yarn build:css --watch"
