x-assets: &default-assets
  build:
    context: "."
    target: "ruby"
    args: 
      - "RAILS_ENV=${RAILS_ENV:-production}"
      - "NODE_ENV=${NODE_ENV:-production}"
  tty: true
  volumes:
    - ".:/app"

services:
  js:
    <<: *default-assets
    command: "yarn build --watch"
